
Group.direction_of_castle(AbPos.new(0,0)).test("")
Group.direction_of_castle(AbPos.new(0,1)).test(/南(?![東西])/)
Group.direction_of_castle(AbPos.new(1,1)).test(/南西/)
Group.direction_of_castle(AbPos.new(1,0)).test(/(?<!南北)西/)
Group.direction_of_castle(AbPos.new(1,-1)).test(/北西/)
Group.direction_of_castle(AbPos.new(0,-1)).test(/北(?![東西])/)
Group.direction_of_castle(AbPos.new(-1,-1)).test(/北東/)
Group.direction_of_castle(AbPos.new(-1,0)).test(/(?<!南北)東/)
Group.direction_of_castle(AbPos.new(-1,1)).test(/南東/)
Group.direction_of_castle(AbPos.new(30,10)).test("王都は西の方向。")
