
BlockKingUI.direction_of_castle(AbPos.new(0,0)).test("")
BlockKingUI.direction_of_castle(AbPos.new(0,1)).test(/南(?![東西])/)
BlockKingUI.direction_of_castle(AbPos.new(1,1)).test(/南西/)
BlockKingUI.direction_of_castle(AbPos.new(1,0)).test(/(?<!南北)西/)
BlockKingUI.direction_of_castle(AbPos.new(1,-1)).test(/北西/)
BlockKingUI.direction_of_castle(AbPos.new(0,-1)).test(/北(?![東西])/)
BlockKingUI.direction_of_castle(AbPos.new(-1,-1)).test(/北東/)
BlockKingUI.direction_of_castle(AbPos.new(-1,0)).test(/(?<!南北)東/)
BlockKingUI.direction_of_castle(AbPos.new(-1,1)).test(/南東/)
BlockKingUI.direction_of_castle(AbPos.new(30,10)).test("王城は西の方向。")
